### ISSUE TITLE
Aardvark.Data.Points.Base: different license in github repo and nuget

### ISSUE THREAD

**Issue by hindikaynen** [aardvark-platform/aardvark.algodat#27]
https://www.nuget.org/packages/Aardvark.Data.Points.Base/ -> License Info -> AGPLv3
https://github.com/aardvark-platform/aardvark.algodat/blob/master/src/Aardvark.Data.Points.Base/LICENSE -> apache 2.0

which one is correct?

**Comment by stefanmaierhofer** [comment]
Apache 2.0 is correct

if a library has its own LICENSE file it overrides the repository (top-level) license file
sorry for the confusion

**Comment by hindikaynen** [comment]
Thank you for the answer.
